---
title: "Cleaning intervention data"
author: "Sara Colom"
date: "`r Sys.Date()`"
output: 
  github_document:
    df_print: kable
---


```{r, warning = F, message = F}
source("R/helpers.R")
```


Quick look at the data

```{r}
int_dat %>% 
  glimpse()
```

# Check data missingness


```{r}
var_ls <- names(int_dat)

missing_count <- purrr::map2_df(rep(list(int_dat), length(var_ls)), var_ls, missing_count) %>% 
        mutate(across(where(is.numeric), ~round(.x, 3))) %>% 
        arrange(desc(freq_missing))

missing_count
```

Display data missing-ness.

```{r}
missing_count %>% 
  ggplot(aes(reorder(variable, -freq_missing), freq_missing)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1)) +
  ylab("Frequency of missing data") +
  xlab("Variable") +
  scale_y_continuous(labels = scales::percent) 

```

Counts of intervention types.

```{r}
int_type <- int_dat %>% 
        select(id, matches("type")) %>% 
        pivot_longer(matches("type"), names_to = "intervention") %>% 
        filter(!is.na(value)) %>% 
        mutate(value = clean_characters(value))

int_type %>% 
  count(value)
  
```



